<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11074" started-at="2016-07-13T13:25:48Z" finished-at="2016-07-13T13:25:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11074" started-at="2016-07-13T13:25:48Z" finished-at="2016-07-13T13:25:59Z">
      <class name="module1.NewTest">
        <test-method status="PASS" signature="initailizedSelenium()[pri:0, instance:module1.NewTest@b30e9f8]" name="initailizedSelenium" is-config="true" duration-ms="7" started-at="2016-07-13T16:25:48Z" finished-at="2016-07-13T16:25:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initailizedSelenium -->
        <test-method status="PASS" signature="testYoutube()[pri:1, instance:module1.NewTest@b30e9f8]" name="testYoutube" duration-ms="11018" started-at="2016-07-13T16:25:48Z" finished-at="2016-07-13T16:25:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testYoutube -->
        <test-method status="FAIL" signature="TestSetting()[pri:3, instance:module1.NewTest@b30e9f8]" name="TestSetting" duration-ms="41" started-at="2016-07-13T16:25:59Z" finished-at="2016-07-13T16:25:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at module1.NewTest.TestSetting(NewTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSetting -->
        <test-method status="PASS" signature="endSelenium()[pri:0, instance:module1.NewTest@b30e9f8]" name="endSelenium" is-config="true" duration-ms="0" started-at="2016-07-13T16:25:59Z" finished-at="2016-07-13T16:25:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSelenium -->
      </class> <!-- module1.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
